"""migration file

Revision ID: 638b7869ed79
Revises: 
Create Date: 2022-11-13 19:14:24.163534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638b7869ed79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_sender_id', sa.Integer(), nullable=True),
    sa.Column('message_receiver_id', sa.Integer(), nullable=True),
    sa.Column('message_content', sa.String(length=5000), nullable=True),
    sa.Column('message_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_delivered', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['message_receiver_id'], ['ryan.user.user_id'], ),
    sa.ForeignKeyConstraint(['message_sender_id'], ['ryan.user.user_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    schema='ryan'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message', schema='ryan')
    # ### end Alembic commands ###
